[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#D4AF37"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111113"
textColor = "#FFFFFF"
font = "sans serif"
